### ISSUE TITLE
Third line not printing

### ISSUE THREAD

**Issue by agb80** [OpenPymeMx/ProxyPoS#1]
Pasting here for reference!!

hi,
i'm having trouble for printing the third line and next lines (it's working normal for the first and second line), it's always getting error on simplejson parse error " TypeError: Expected string or buffer".
I'm wondering if you already knew about this issue, btw i'm using Ubuntu 13.04, Python 2.7.4, and my OpenErp server version is 7.0-20131031-002505

**Comment by rovyxbiztech** [comment]
Yes this is happening for me too. Raspberry Pi running Raspbian 3.10.24, Python 2.7.3, OpenERP 7.0-20131211.

Any solution for this so far?

**Comment by agb80** [comment]
A fix for this has been committed on develop branch. Please test it and appreciate if you could confirm that is solver for merge into master.

**Comment by rovyxbiztech** [comment]
It is solved for printing but there is an additional error which results in '500 Internal Server Error'

2013-12-29 05:16:33,853 - proxypos.app - INFO - Procesing /pos/print_receipt GET method
Traceback (most recent call last):
  File "/home/proxypos/proxypos/proxypos/bottle.py", line 861, in _handle
    return route.call(*_args)
  File "/home/proxypos/proxypos/proxypos/bottle.py", line 1755, in wrapper
    rv = callback(_a, **ka)
  File "/home/proxypos/proxypos/proxypos/app.py", line 191, in print_receipt
    logger.debug('Params %s', str(params['r']))
KeyError: 'r'

**Comment by agb80** [comment]
Sorry for late answer, we were on vacations for holidays, we are getting back on office since today and hope all the communication will be improved.

I just push a new version on development branch solving the error you are posting. Please update your code and if anything else is wrong report on a new issue.

Thanks in adavance
