### ISSUE TITLE
Can't start proxypos-server (error 98) Address already in use

### ISSUE THREAD

**Issue by josugm** [OpenPymeMx/ProxyPoS#11]
When I try to start proxypos-server I always get this error at the end.

socket.error: [Errno 98] Address already in use.

When I kill the process that is blocking proxypos-server to start, It starts, but when trying to access by web browser it gives an error 404.
Not found: '/'

**Comment by agb80** [comment]
By the symptoms you describe I'm guessing that you are using ProxyPoS on the same machine where you installed the OpenERP server. 

Even it is possible, is not recommended, ProxyPoS was designed to be used on the client machines where you are actually running your cashier box.

If you want to use ProxyPoS on same box than OpenERP, you are going to need to change the port ProxyPoS is listening. In the configuration file look for the port directive and change the 8069 for any other you want.

Also you are going to need to edit your point of sale javascript, this line for be precise: https://github.com/Fedrojesa/Point-of-Sale-Enhanced/blob/master/point_of_sale/static/src/js/devices.js#L11
to match the same port you decide to use for ProxyPoS
