### ISSUE TITLE
Mejoras a Proxypos 1.2

### ISSUE THREAD

**Issue by florca1979** [OpenPymeMx/ProxyPoS#12]
proxypos  odoo 8 compatibility

**Comment by agb80** [comment]
Hello, we are just starting to use Odoo 8, as soon as we can we would upgrade ProxyPoS to allow compatibility with it.

**Comment by effelle** [comment]
Hi, 
is still not compatible with Odoo 8.0? 

It compiles well but is giving me an error about an address already in use:

effe@serverdivina:/tmp/proxypos$ proxypos-server
2015-03-23 16:29:37,482 - proxypos.proxypos - INFO - ProxyPos server starting up...
2015-03-23 16:29:37,482 - proxypos.proxypos - INFO - Listening on http://localhost:8069/
Traceback (most recent call last):
  File "/usr/local/bin/proxypos-server", line 5, in <module>
    pkg_resources.run_script('proxypos==1.2.0', 'proxypos-server')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/EGG-INFO/scripts/proxypos-server", line 5, in <module>
    proxypos.main()
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/**init**.py", line 64, in main
    quiet=True)
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/bottle.py", line 3050, in run
    server.run(app)
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/bottle.py", line 2704, in run
    srv = make_server(self.host, self.port, app, server_cls, handler_cls)
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 144, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in **init**
    self.server_bind()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 48, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

I'm trying to configure an USB thermal printer to print automatically my KOT using the Restaurant POS module. The printer works fine.

Any clue?

**Comment by effelle** [comment]
Ok. I've already an half reply.
proxypos is istening at http://localhost:8069/, or at http://0.0.0.0:8069/ (depending by the configuration) but the address and the port are already used by odoo. If I stop the odoo server proxypos starts just fine but... No odoo, even restarting the server.
I'm just starting to doubt this is not the solution for my problem, I don't know if your module apply to print by proxy option for the kot. Am I wrong?

**Comment by agb80** [comment]
Sorry for not being able to answer earlier.

As Odoo and ProxyPoS use the same port for listen to information, ProxyPoS is not intended to be used on the same machine than OpenERP/Odoo, but instead on a separated PoS terminal. That's why you are not able to run both services at the same time.

**Comment by effelle** [comment]
Then is not what I'm looking for. Thanks anyway Agustin, have a nice day!

**Comment by effelle** [comment]
Agustin, 
having the odoo server on a machine and a pos on a second machine could be ok, but how about a tablet? Did you manage to use it or is not possible?

**Comment by agb80** [comment]
Hello again, this software could be listen to any address on local network. For the scenario you are detailing will be two solutions:
1. Install ProxyPoS on a any PC or Mac box available on your local network and redirect the PoS javascript to look for ProxyPoS on a network IP instead of localhost.
2. If not other box available on local network, install ProxyPos on a RasperryPi or similar device and also redirect the PoS javascript for look for ProxyPos on a network IP

**Comment by effelle** [comment]
Interesting Agustin! Then should be possible to install ProxyPoS on a VM, connect the printer on it and set Odoo's proxy address to the VM.  I'll check it ASAP.

**Comment by effelle** [comment]
OK. I've tried with both VM (alternatively with Odoo or ProxyPoS) and physical machines.
On one is installed a fresh, new Odoo 8 with ESC/POS module and the ip 192.168.0.104, on another the Proxypos listening to 0.0.0.0:8069 and with the usb thermal printer correctly configured. For this machine I've assigned the IP 192.168.0.25.  
On the Odoo PoS I set as a proxy the ip 192.168.0.104 (print via proxy and cashdrawer enabled) with or without ports (9100 or 631) and I started the ProxyPoS server before Odoo server.
The message on Odoo logs is always the same:  ESC/POS Device Disconnected: Printer Not Found.

Am I missing something?

F.

Edit:
I forgot to say there are no errors on ProxyPos Log.

**Comment by agb80** [comment]
The published version of ProxyPoS is not compatible with Odoo v8.0. 

Our customers still using OpenERP v7.0, and there were no one interested on support us for make the migration. If you would like to fund us for make this migration please contact us on info @ openpyme.mx

**Comment by effelle** [comment]
Ok. Understood, I tough it was compatible with V8 my mistake. Time to buy a Epson then and use it with Odoo V8 (or V9). I can afford to pay a new module just for a printer now, considering I have already resolve my urgency... 

https://www.odoo.com/forum/help-1/question/print-order-instead-of-coupon-on-pos-what-qweb-view-82635 

But thanks Agustin I'll think on it.
