### ISSUE TITLE
Error with character encoding

### ISSUE THREAD

**Issue by hydrosIII** [OpenPymeMx/ProxyPoS#14]
Hello, after a while im back at looking at your library.

I have succesfully set up everything, and it almost working with openerp 7

However when printing  the receipt from openerp i get the following error, in character encoding. The printing stops and it just prints a few lines, but it does print a little.

The character that stops the printing is an é

I get the foillowing error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/app.py", line 90, in do_print
    device.print_receipt(receipt)
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/controlers/printer.py", line 85, in print_receipt
    self._write(str(receipt['company']['contact_address']) + '\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 60: ordinal not in range(128)

I have tried enabling the different encodings in the yaml config file, even enabling every encoding at the same time doesn't solve the problem.

I have installed proxyPos last version from master.
Also the python ESC/POS from your repo, master branch also.

Im using Debian Wheezy.

Version of the python libraries, some installed using pip, others with apt.

PIL==1.1.7
PyYAML==3.10
chardet==2.0.1
escpos==2.7
numpy==1.6.2
obMenu==1.0
paramiko==1.7.7.1
pexpect==2.4
proxypos==1.2.0
pycrypto==2.6
pycurl==7.19.0
pyserial==2.5
python-apt==0.8.8.2
python-debian==0.1.21
python-xlib==0.14
pyusb==1.0.0b2
pyxdg==0.19
qrcode==5.1
rpl==1.5.5
simplejson==2.5.2
six==1.8.0
wsgiref==0.1.2
wxPython==2.8.12.1
wxPython-common==2.8.12.1

**Comment by agb80** [comment]
Thank you for your detailed report, let me investigate on this and going to get back to you in a couple of days
