### ISSUE TITLE
Error: 404 Not Found  

### ISSUE THREAD

**Issue by jayo2005** [OpenPymeMx/ProxyPoS#19]
I installed Proxypos on my client till. Started proxypos-server.
proxypos.proxypos - INFO - Listening on http://0.0.0.0:8069/

If I go to localhost:8069 on my client till should it tell me connected devices. At the moment I am getting
Error: 404 Not Found

Sorry, the requested URL 'http://localhost:8069/' caused an error:

Not found: '/

Should I be seeing something on this address? I know this is not my Odoo instanace but should I see connected devices etc..

**Comment by agb80** [comment]
Not, at this momment there is no page for display devices information.

**Comment by jayo2005** [comment]
Does it work with odoo9

**Comment by agb80** [comment]
Never test it but I don't think so, the project was developed for a customer on OpenERP v7.0, not migrated any further
