### ISSUE TITLE
Installation steps for Windows XP?

### ISSUE THREAD

**Issue by ericmachine88** [OpenPymeMx/ProxyPoS#2]
Like to check. What if my POS is running on Windows XP instead of Linux Mint, how can I make this work? Any help? Thanks.

**Comment by agb80** [comment]
Currently we don't have a set of installation instructions for XP as we not use that S.O. anymore. 

This week we are going to be on holidays, but if you could wait for january, we can separate some time for test it and create a installation instruction.

In the mean time, if you would like to start investigating, you could try installing python 2.7 (http://sourceforge.net/apps/trac/libusb-win32/wiki) and libusb-win32 (http://www.python.org/getit/).

**Comment by ericmachine88** [comment]
Okay, I will give this a try on Windows XP using your recommendation.

Happy Holidays and a Happy New Year in advance to you :)

**Comment by donmuri** [comment]
Any update on this?

**Comment by damoandsusie** [comment]
Hi Chaps,
Any news on XP instructions? Sadly whilst most of us have Linux OpenERP srrvers the majority of PoS terminals still run windows. Installation instructions for the client on Windows terminals would be very helpful. 
Also is tje customer display module workinf on OpenERP 7 yet? If so do you have windows instructions for that too?
Thanks in advance!

**Comment by agb80** [comment]
Some user have reported use proxypos on Win 7 with ethernet printer without problem. Not currently on our priority list because as I have told we not use XP any more.

**Comment by agb80** [comment]
At this time we have a working exe for Win7/8 please contact us at info@openpyme.mx if you are interested.
