### ISSUE TITLE
Receipt Width

### ISSUE THREAD

**Issue by donmuri** [OpenPymeMx/ProxyPoS#4]
I have tried the update branch. Here is what I got:

1) The printer still prints at 44 charWidth. My paper size is 80x297mm which is roughly 55 charWidth. I tried changing the values but it is still the same.

2) Is there limitation to what the template can pull from OpenERP? I cant pull the company tagline which is "rml_header1" to be printed out.

3) "Change" value remains at 0.

4) Logo seems even worse after the new update.

I can provide a screenshot of my result if needed. Let me know.

**Comment by agb80** [comment]
Let's going to work one by one the issues you are having. Could you please upload a screenshot and the image you are trying to print please.

**Comment by donmuri** [comment]
The first image is the receipt printed. I didnt not crop the top of the receipt, it printed out that way. The second image is the logo Im trying to include into the receipt. From the scan, you can see how the text are not properly aligned, change value doesnt show and the logo as well.

**Comment by donmuri** [comment]
I found the solution for the width issue. I have to change the value at the bottom of the script where font == 'a'. Should I open another issue for the logo or we can continue here?

**Comment by agb80** [comment]
I have uploaded a new commit on develop branch with the change you commented regarding the width issue.

**Comment by agb80** [comment]
Regarding the logo, do you have available an image with out the blue background? And yes, better move to a new issue. Thanks in advance!
