### ISSUE TITLE
Cant print logo out

### ISSUE THREAD

**Issue by donmuri** [OpenPymeMx/ProxyPoS#5]
I tried using this image from google:

http://jpgraph.net/download/manuals/chunkhtml/images/qr-code-small.png

Cant print out the logo properly.

It produces one line of image as per below:

**Comment by donmuri** [comment]
For the record, the logo worked when I use master branch last time. I have compared between master and develop to see modification that may affect logo printing but I could not detect any.

**Comment by agb80** [comment]
I think I figure where the problem is, could you try please change line at:
https://github.com/Fedrojesa/ProxyPoS/blob/develop/proxypos/controlers/printer.py#L85

from:

```
self._printImgFromFile(filename)
```

to:

```
self.printer.image(filename)
```

**Comment by donmuri** [comment]
I receive mixed results. Sometimes it works sometimes it doesnt. And error log doesnt show anything. Here is the printed output when it doesnt work using logo.jpg provided.

**Comment by donmuri** [comment]
i tried printing using PIL still doesnt work

**Comment by agb80** [comment]
Would you mind try using Pillow, because I can't reproduce your behavior.

**Comment by donmuri** [comment]
I have tried Pillow. I tried using the python image library to manipulate the logo first then printing it out, still the same result. I am using Partner RP320

**Comment by agb80** [comment]
Ok, regarding your comment: "For the record, the logo worked when I use master branch last time. I have compared between master and develop to see modification that may affect logo printing but I could not detect any."

The change is that on last master branch we were using the image function as comes out of the box on this library: https://github.com/agb80/python-escpos and on develop branch we are using a custom function for better performance.

Could you please try on python console with this commands for check if the problem is with our custom function or with the base library please:

```
from escpos import printer
device = printer.Usb(idVendor, idProduct)
device.image(filename)
```

Just ensure to substitute idVendor & idProduct with the correct data from your printer and please try several times to discover if you have the same mixin results as before.

**Comment by donmuri** [comment]
using your test, it prints out properly. no issue at all. i tried using the same code and place it inside the printer.py. the printer will printer random characters and stop just before the print logo starts and it did not print fully. can it be my library? for the record, im using master branch now.

**Comment by agb80** [comment]
Could you please copy/paste your print_receipt function, seems there is no problem with base library.

**Comment by donmuri** [comment]
```
def print_receipt(self, receipt):
    """ Function used for print the recipt, currently is the only
    place where you can customize your printout. 
   """
    # abc = printer.Usb(0x0525, 0xa700)
    # abc.image('/home/proxypos/proxypos/proxypos/controlers/image003.jpg')

    # path = os.path.dirname(__file__)
    # filename = path + '/small_logo.png'
    # self.printer.pxWidth = 206
    # self.printer.image("/home/proxypos/proxypos/proxypos/controlers/small_logo.png")

    # self._printImgFromFile(filename)

    # im = Image.open("/home/proxypos/proxypos/proxypos/controlers/small_logo.png")
    # im = im.filter(ImageFilter.CONTOUR)
    # im.save("/home/proxypos/proxypos/proxypos/controlers/small_logo.jpg")

    # self._printImgFromPILObject(filename)

    # self._printImgMatrix(im)

    date = self._format_date(receipt['date'])
    self._bold(False)
    self._font('a')
    self._lineFeed(1)
    self._write(date, None, 'center')
    self._lineFeed(1)
    self._write(receipt['name'] + '\n', '', 'center')
    self._lineFeed(1)

    self._write(receipt['company']['name'] + '\n', '', 'center')
    self._write('Company Registry: ' + str(receipt['company']['company_registry']) + '\n', '', 'center')
    self._write('Telephone: ' + str(receipt['company']['phone']) + '\n', '', 'center')
    self._write('Cashier: ' + str(receipt['cashier']) + '\n', '', 'center')
    self._write('-----------------------------------------------------', '', 'center')
    # self._write('Tienda: ' + receipt['store']['name'])
    self._lineFeed(1)
    for line in receipt['orderlines']:
        left = str(line['quantity']) + ' ' + str(line['unit_name']) + ' ' + str(line['product_name'])
        right = self._decimal(line['price_with_tax'])
        self._write(left, right)
        self._lineFeed(1)

    self._lineFeed(2)
    self._write('Subtotal:', self._decimal(receipt['total_without_tax']) + '\n')
    self._write('Total Tax:', self._decimal(receipt['total_tax']) + '\n')
    self._write('Discount(s):', self._decimal(receipt['total_discount']) + '\n')
    self._write('-----------------------------------------------------', '', 'center')
    self._bold(True)
    self._lineFeed(1)
    self._write('TOTAL:', '$' + self._decimal(receipt['total_with_tax']) + '\n')
    self._write('-----------------------------------------------------', '', 'center')

    # Set space for display payment methods
    self._lineFeed(1)
    self._font('a')
    self._bold(False)
    for payment in receipt['paymentlines']:
        self._write(payment['journal'], self._decimal(payment['amount']))
    self._lineFeed(1)
    self._write('Change:', '$ ' + self._decimal(receipt['change']))
    self._bold(False)

    # Write customer data
    client = receipt['client']
    if client:
        self._lineFeed(4)
        self._write('Client: ' + client['name'].encode('utf-8'))
        self._lineFeed(1)
        self._write((u'Telephone: ' + client['phone']).encode('utf-8'))
        self._lineFeed(1)
        self._write('Address: ' + client['contact_address'].encode('utf-8'))
        self._lineFeed(4)

    # Footer space
    self._bold(True)
    self._write('Thank you and please come again!', '', 'center')
    self._lineFeedCut(1, True)
```

**Comment by donmuri** [comment]
any update on this?

**Comment by agb80** [comment]
I have pushed a new branch named release-1.1.0 where replaced PIL with Pillow. Please try it and let me know if that fixes your problem.

For Pillow installation instructions see here: http://pillow.readthedocs.org/en/latest/installation.html

**Comment by donmuri** [comment]
I have fixed the issue.

I had to add an empty line(self._lineFeed(1) or self._write('\n')) above the print image code to allow the space required for the image to be printed out. Also, I used self.printer.image("logo.jpg") instead.

**Comment by crisjff** [comment]
Hello **agb80**, this is a great project, thank you for sharing.
I had test it with Zonerich thermal printers (http://www.zonerich.com/goods_list.php?id=43), connected by USB or serial on Kubuntu OS 14.04 -> OpenERP 7. 
Everything works fine so far, except the USB link that only prints once, then I have to restart proxy-server, and the logo print that is cut by several lines. I use the PIL version (don't know the release), where could I find the Pillow version? I also try `self.printer.image(filename)`, but the result was the same. ![logo0002](https://cloud.githubusercontent.com/assets/3230287/12371581/ec96ccc4-bc38-11e5-961a-9132d39a8dda.png)
Thank you for your time and attention, and once again **great project!**

**Comment by agb80** [comment]
Hello @crisjff unfortunately we are being very slow to maintain this module but for now you can use the templates branch that is the most stable one: https://github.com/OpenPymeMx/ProxyPoS/tree/templates

On that branch the problem with USB printers that only prints one is solved and is the pillow version so I'm hope the problem with logo is solved too.

**Comment by crisjff** [comment]
OK, thank you for your reply, I will give it a try and feed back.

2016-01-18 18:45 GMT+01:00 agb80 notifications@github.com:
