### ISSUE TITLE
Lubuntu setup / New printer

### ISSUE THREAD

**Issue by mamolas** [OpenPymeMx/ProxyPoS#7]
Hello,
I'm trying to print from POS80mm based on EPSON (ESC/POS) Thermal printer standard, browser is running on Lubuntu, OpenERP installed at AWS EC2 Cloud server, but couldn't done succesfully not even from Windows browser: different browsers different bad presentation,  will the Mint steps work the same on Lubuntu 14.04?

If its not the same, is there an easier way to print simply buying another printer ready for OpenERP7, which one?

Thanks!

**Comment by agb80** [comment]
Hello, first of lat thank you for give an opportunity to our software. The ProxyPoS supports any Esc/PoS compatible printer and for my knowledge is the simple and easy way to make your printer work with OpenERP PoS on high quality.

A priori the installation procedure will be almost the same, but don't have prove it so cannot be 100% sure, even if you found any trouble with the installation steps just let me know and I will be pleased to help you as much as I can.

PD: On the Todo list it's an installer for simplify software setup

**Comment by agb80** [comment]
Launching the new version with simple installation, just closing this.
