### ISSUE TITLE
cannot print to serial port. 

### ISSUE THREAD

**Issue by hydrosIII** [OpenPymeMx/ProxyPoS#9]
I cannot print to my serial port printer i got:

SerialException: Could not configure port: (22, 'Invalid argument')

when trying to send something to the printer.

**Comment by hydrosIII** [comment]
Ok rechecking all my configurations i just figured out. What is a serial port?? 
I just figured this is a serial port:
http://en.wikipedia.org/wiki/Serial_port

I was trying to make my printer print form a PARALELL port.
http://es.wikipedia.org/wiki/Puerto_paralelo

which seems to be different kind of port, not speaking the same language as the serial port.
checking the page of pyserial, seemed to be a project called pyparallel but it was abandoned. Is the communication really different, that is impossible to send instructions to paralell port?. I can send raw text via echo or cat to the parallell port located in /dev/lp0 without problem. My printer is an Epson TMT88 V. Can i just convert to parallel port to usb port with a cable???.

In this type of printer you can exchange port  to usb or serial, if none of the above can be done, i will buy this new port to try it. Sorry for the confusion , but it was because serial ports are not used anymore, i just thought serial port, was and "old" port, not researching in depth.

Thanks

**Comment by agb80** [comment]
Serial port refers to the communication protocol, not the kind of connector or something like that, and yes is very different the serial protocol than the parallel protocol.

When you send raw text you are using native linux driver for communicate with your device. Of course you can develop an interface for use that driver with ProxyPoS but is out of the scope of our development.

There are adapters parallel to usb but I'm not sure it's going to work.
